builds:
  37594b17679330746d0f87a5aad26b4e63be8732d5245f485a93d5142f9c1e92:
    version: 37594b17679330746d0f87a5aad26b4e63be8732d5245f485a93d5142f9c1e92
    blobstore_id: a15e9c9b-b970-421b-76d2-d9aa91a29512
    sha1: sha256:a992e730590873750338269ec20294a8e48d88b01b540863ece336bb1832d20d
  afb6890f7b0cffb416ac038e05ebe5d02efd19889dab70f5594c62bdd66d0016:
    version: afb6890f7b0cffb416ac038e05ebe5d02efd19889dab70f5594c62bdd66d0016
    blobstore_id: 46c6e3f5-dbb7-4726-44d7-7a61fc819fb1
    sha1: sha256:038393d367b283e0d65b8e25dfad50cbae5842b40d7fd3b89d9ca69f93c97f61
format-version: "2"
