builds:
  206021a5f239b0e9d8d583384773fb47cbc4258fb03ea6ba43b7e31c72d5ffa2:
    version: 206021a5f239b0e9d8d583384773fb47cbc4258fb03ea6ba43b7e31c72d5ffa2
    blobstore_id: 3d4d4b9b-02b8-4bf9-6a27-96d71108e73d
    sha1: sha256:6b3040f3a9a10b0a7f088bf3de76b474cab7cc9a43d4068a586fb780ce6a3040
  29b6ac4eacd379e6ce568d2bc30c34a71ed57c9e8124bfa3439fc6368986e48c:
    version: 29b6ac4eacd379e6ce568d2bc30c34a71ed57c9e8124bfa3439fc6368986e48c
    blobstore_id: 4c95eb4d-07a4-4a31-4432-4880379f27d8
    sha1: sha256:2a51ef400ae03edf730cbf873cb4904f10415a7af386f5c443b9d9bfd42fa16b
  cd0a9dab762e16f55f7d9a8c00dfcf2fbfb27ed00128b08d6c86f971ba9762b8:
    version: cd0a9dab762e16f55f7d9a8c00dfcf2fbfb27ed00128b08d6c86f971ba9762b8
    blobstore_id: 72f765f9-56ac-48c1-6400-feafcae30e79
    sha1: sha256:658b2677318520bcccc8dd308c39517b81288672ec44ca00208488063fb68a77
  f30be75cbbf62f2aee99fcbcbf143309dddeaa2cb6912aef086f04a179759e3e:
    version: f30be75cbbf62f2aee99fcbcbf143309dddeaa2cb6912aef086f04a179759e3e
    blobstore_id: 10fb95eb-9884-4af9-61ed-152f4c99a53e
    sha1: sha256:9a93d8bfcd2b59b1de7380fa1f6c47e6246ce083cbeda056ee8a101f0c54140b
format-version: "2"
