autoconf-2.69.tar.gz:
  size: 1927468
  object_id: 2e4a01bd-aa1e-4fbc-5f56-80aa40d805e3
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
automake-1.15.tar.gz:
  size: 2244206
  object_id: 50feb35a-e388-4fb0-4313-3a47e82fad22
  sha: b5a840c7ec4321e78fdc9472e476263fa6614ca1
cifs-utils-6.7.tar.bz2:
  size: 363647
  object_id: c529967d-57fa-4b41-685e-ff0a507ffaad
  sha: 9ba5091d7c2418a90773c861f04a3f4a36854c14
cni/cni-plugins-amd64-v0.7.1.tgz:
  size: 17108856
  object_id: 50dc58eb-107d-483a-4e37-5a243ffed520
  sha: fb29e20401d3e9598a1d8e8d7992970a36de5e05
cni/util-linux_2.27.1-6ubuntu3_amd64.deb:
  size: 847730
  object_id: 27eb3ec3-220f-4a25-6c4f-ec219c37ac8d
  sha: 568f62cb031608ab09ba1e3c2121e9e8b92dcae4
common-core-kubernetes-1.17.3+vmware.1/kube-apiserver:
  size: 159836595
  object_id: 185ca259-9bbe-4ea4-5c99-3d58a6893831
  sha: 1aa8e0e0e5986cb4e846194cfc8b4c9049bedf61
common-core-kubernetes-1.17.3+vmware.1/kube-controller-manager:
  size: 148336013
  object_id: fdc588a2-5d24-4d65-5b7a-91de9540c5e7
  sha: ec5f686a8ee4a9d05d5c3961c75f790fe1c94343
common-core-kubernetes-1.17.3+vmware.1/kube-proxy:
  size: 51957485
  object_id: 0dfc2510-80cf-48db-67a4-963d63420ecd
  sha: c8584f012930dae0f5f655ed2061af0f25699fe0
common-core-kubernetes-1.17.3+vmware.1/kube-scheduler:
  size: 58057786
  object_id: f9870acc-eb47-4d0a-5ebc-ae69c86204f0
  sha: bc7298140106725f803b7d3a1d789f91847cf6c0
common-core-kubernetes-1.17.3+vmware.1/kubectl:
  size: 59360015
  object_id: 572182dd-8037-4f34-72a3-52d698b04185
  sha: 274f141c636a93b75ba5d3a9dc8da7ec53b1608c
common-core-kubernetes-1.17.3+vmware.1/kubelet:
  size: 150522168
  object_id: de3bb2f2-c13d-47c6-7d11-d74cd61d160e
  sha: 8fc16c2c8e31892055e539d1cec3069500224932
conntrack/conntrack_1.4.3-3_amd64.deb:
  size: 27346
  object_id: 0c4aa633-3de8-4a8c-7170-36b3fc9e4a9c
  sha: sha256:ad9eae1cf2191981dd687b681ee701a2f3adfca5b89b45c2ff74c0f8d32113ff
conntrack/libnetfilter-conntrack3_1.0.5-1_amd64.deb:
  size: 36634
  object_id: 1d6d9546-e933-46bd-60f9-00bd8eb91c59
  sha: sha256:18609b2b131bc0dedf4a2c3fbf61b30d16c3d3a96cd43d604e8fc53ebc1e30eb
container-images/vmware_coredns:1.6.2.tgz:
  size: 13962465
  object_id: 6973437f-757e-4a19-7278-0c3403f9d51c
  sha: sha256:8e5e64cf3b93a3e5c40e734deaf53420af2fbbd864dce8618158616686ece78f
container-images/vmware_metrics-server-amd64:v0.3.6.tgz:
  size: 12062146
  object_id: 301b9879-c1bf-42bb-6d90-f05929118056
  sha: sha256:cc477697ea176696030955ed413dc3be064c91a32735458f6450602eddd8f11d
container-images/vmware_nginx-bionic:1.0.0.tgz:
  size: 66797183
  object_id: 370b05ca-2ad8-4f1b-6002-22ea8ce709fc
  sha: sha256:27ed75ab7de88b3b58c5117357eee4baa77e53140b3cba7ed3f678a0bfa253ee
container-images/vmware_pause:3.1.tgz:
  size: 314768
  object_id: 2224d7c6-0395-49ea-7356-0b04d413e8ae
  sha: sha256:8b7f7da2677ac899f712ea89cb2f0683f8a42c8cd339512c58df0aa4d162e8cb
ctop/ctop-0.5.1-linux-amd64:
  size: 5667856
  object_id: df4344f1-26d6-453c-52da-e728cb94332a
  sha: sha256:2b49a5e5343f027ddd4dc64be938e6ae668ac14e1117e8541c29308442f4a381
docker/autoconf-2.69.tar.gz:
  size: 1927468
  object_id: f762b758-4190-468f-556a-0f1cb17f2a1a
  sha: sha256:954bd69b391edc12d6a4a51a2dd1476543da5c6bbf05a95b59dc0dd6fd4c2969
docker/bridge-utils-1.5.tar.gz:
  size: 33472
  object_id: 8235dfbc-d475-4b0f-7682-cc912fc8fdcd
  sha: sha256:80c18ef50bff135f406bfc503ca832f9e3a33f314cce85717a4dbd2b36409bd2
docker/docker-19.03.5.tgz:
  size: 63252595
  object_id: f7394f5c-f3fb-47ec-4520-b25b6d9c49a0
  sha: 05ab09d78e77db7fd4d252cb7bf986f5b9035e09
etcd/etcd-v3.3.12-linux-amd64.tar.gz:
  size: 11350736
  object_id: b46e6432-ea27-4a54-56ba-87692b3b6cb1
  sha: sha256:dc5d82df095dae0a2970e4d870b6929590689dd707ae3d33e7b86da0f7f211b6
etcd/etcd-v3.3.17-linux-amd64.tar.gz:
  size: 14222547
  object_id: 6655b472-a992-4760-4798-066690cd6804
  sha: sha256:8c1168a24d17a2d6772f8148ea35d4f3398c51f1e23db90c849d506adb387060
flannel-v0.11.0-linux-amd64.tar.gz:
  size: 9565743
  object_id: 83064ebe-b45d-4d41-694a-b1e61a781250
  sha: 3024034b2202d5940acf5353037161ea1770a9c5
ipset/ipset_6.20.1-1_amd64.deb:
  size: 34156
  object_id: 5dfcce8f-366e-49f0-59e6-9e2d48178750
  sha: 79eb9008d1a57b31bc748b49c18701ab3dd41108
ipset/libipset3_6.20.1-1_amd64.deb:
  size: 50812
  object_id: 67efec49-e111-45fc-701d-7d55dbe66660
  sha: e4daa1ac22b2775d1c334aa6fe055ca8dcccc185
jq-linux64-1.6:
  size: 3953824
  object_id: efdcc8cd-7155-47d4-65c9-d3d74700633f
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
libmnl0_1.0.3-5_amd64.deb:
  size: 11970
  object_id: 30b1e2c0-4194-47f2-544f-f55eb76b9101
  sha: sha256:abd749bdd206e51fc9ac19ef27d4452a2d9df46b5b1a276d50a065af901ab1c4
libtool-2.4.6.tar.gz:
  size: 1806697
  object_id: 670cc8a2-75d8-4fb5-465f-270395cb9373
  sha: 25b6931265230a06f0fc2146df64c04e5ae6ec33
nfs-debs/keyutils_1.5.9-8ubuntu1_amd64.deb:
  size: 47054
  object_id: e1b42c34-4e88-426b-7268-99d1bdfd40c1
  sha: ec2e96e73feb5215605c9f0254cad05d9cc5688a
nfs-debs/libevent-2.0-5_2.0.21-stable-2ubuntu0.16.04.1_amd64.deb:
  size: 114014
  object_id: 0fa38188-cd2c-417f-7407-02367bc99c7d
  sha: sha256:e1acdffde386a4da7de46166ffd199771a13498f5d4fc38d61b3fa0eba305572
nfs-debs/libnfsidmap2_0.25-5_amd64.deb:
  size: 32182
  object_id: 59ba4d66-fb63-4a62-75da-8502169d85cd
  sha: f28b7370542daaf81cefb44d9057fa9b3fb43064
nfs-debs/nfs-common_1:1.2.8-9ubuntu12.1_amd64.deb:
  size: 184334
  object_id: 6c99be77-1ba2-4be4-409a-36c090035646
  sha: 38f7234fade7c15ffecf4c043c877b01ead92d3d
nfs-debs/rpcbind_0.2.3-0.2_amd64.deb:
  size: 40252
  object_id: 56ad455e-38be-40da-7815-a9d4774d55e4
  sha: 8fa58cfcb1862c6d337d10496fada5f1a6e94a03
pkg-config-0.29.2.tar.gz:
  size: 2016830
  object_id: 2a0b553f-c65d-42ef-6317-dd0cfcdc7c06
  sha: 76e501663b29cb7580245720edfb6106164fad2b
socat-1.7.3.2.tar.gz:
  size: 615818
  object_id: a6f3dcb3-54a0-44a3-4100-f408932aaf8f
  sha: a2446f65fb9fe9703b85ac5664c8920089fe32d8
talloc-2.1.9.tar.gz:
  size: 440335
  object_id: f2d8d5e1-1cb6-450c-480f-015534a76b17
  sha: e1e79fec4c0b6bd92be904a9c03b0a168478711a
