autoconf-2.69.tar.gz:
  size: 1927468
  object_id: 2e4a01bd-aa1e-4fbc-5f56-80aa40d805e3
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
automake-1.15.tar.gz:
  size: 2244206
  object_id: 50feb35a-e388-4fb0-4313-3a47e82fad22
  sha: b5a840c7ec4321e78fdc9472e476263fa6614ca1
cifs-utils-6.7.tar.bz2:
  size: 363647
  object_id: c529967d-57fa-4b41-685e-ff0a507ffaad
  sha: 9ba5091d7c2418a90773c861f04a3f4a36854c14
cni/cni-plugins-amd64-v0.8.7+vmware.3.tgz:
  size: 39810209
  object_id: 137a8783-fc99-4811-78b6-e85d878ec289
  sha: sha256:f50c9c152223f03ddbfa0d8deafebce9ea2720ecd838c28aee4e4680ce3be5e3
cni/nsenter-2.27.1:
  size: 27520
  object_id: f78a843e-4bf1-47c4-578b-786fcf8a2c94
  sha: sha256:9999ffda41275f924bcbb1d9d7b129421838d917236511eccacae7dc0ad631a9
common-core-kubernetes-1.18.12+vmware.2/kube-apiserver:
  size: 162415807
  object_id: 2e08674d-746c-4c86-57d8-1238ac5cfa8e
  sha: sha256:ff2549726aeee613d28063937b2154f48f16559ea11c8bb9dc00b3a7c1b3a8a1
common-core-kubernetes-1.18.12+vmware.2/kube-controller-manager:
  size: 150267407
  object_id: 7eb9b450-036f-4f55-5142-28cb474ba919
  sha: sha256:4a9a15f48a9725a51ec297127fe559619ef140b0711f224951f330327a1e0e83
common-core-kubernetes-1.18.12+vmware.2/kube-proxy:
  size: 52725667
  object_id: 14933d73-ff60-461c-5c2c-e6ef6224dac6
  sha: sha256:a6607e109e834ac4b78b5d84ce64a196c32346b9684392ca24c00d6b14f79673
common-core-kubernetes-1.18.12+vmware.2/kube-scheduler:
  size: 59248826
  object_id: e0e9cc0b-a011-4556-7148-6544b4392caa
  sha: sha256:fe5cb890bd3f755e3f29fcf73df679054102b410fe54281b3eb7347aee277814
common-core-kubernetes-1.18.12+vmware.2/kubectl:
  size: 60078035
  object_id: 5591e69b-56c4-4379-68bc-291464e71924
  sha: sha256:ebd6765109690784247bb9729fba9f0f2da34c322de016c44bcf3f1ad78566ef
common-core-kubernetes-1.18.12+vmware.2/kubelet:
  size: 152768792
  object_id: c1fef481-0ffe-483e-4fd4-3b6d64328a0e
  sha: sha256:60f4631d32746a31a0071b2dda5f92eab00cfcdbb6a86c8c6710bc2b520a4988
conntrack/conntrack_1.4.3-3_amd64.deb:
  size: 27346
  object_id: 0c4aa633-3de8-4a8c-7170-36b3fc9e4a9c
  sha: sha256:ad9eae1cf2191981dd687b681ee701a2f3adfca5b89b45c2ff74c0f8d32113ff
conntrack/libnetfilter-conntrack3_1.0.5-1_amd64.deb:
  size: 36634
  object_id: 1d6d9546-e933-46bd-60f9-00bd8eb91c59
  sha: sha256:18609b2b131bc0dedf4a2c3fbf61b30d16c3d3a96cd43d604e8fc53ebc1e30eb
container-images/simple-server.tgz:
  size: 11953836
  object_id: d362a1a2-0a96-4e73-67a6-2e8565edc489
  sha: sha256:8c0c566079241cb5ec0c6708b47e2ee71b5dc470caa1cef62b0b2c671e784ef8
container-images/vmware_coredns:1.6.7_vmware.6.tgz:
  size: 12202440
  object_id: 89fac37a-f060-4db6-46c5-fd5ad6d50c7a
  sha: sha256:e7e7806ea1203d929435df5a9aec142c443e9b63b775828c852e7365514f3ec7
container-images/vmware_metrics-server-amd64:v0.3.6.tgz:
  size: 12062146
  object_id: 301b9879-c1bf-42bb-6d90-f05929118056
  sha: sha256:cc477697ea176696030955ed413dc3be064c91a32735458f6450602eddd8f11d
container-images/vmware_pause:3.2.tar.gz:
  size: 286604
  object_id: 27038a71-2c6d-4ada-4e4d-705925c8b315
  sha: sha256:a35cc98a91d6c6b9cecccfae0a11ffb2b7c553b77bdf49d4223b762f11d4e7cb
ctop/ctop-0.5.1-linux-amd64:
  size: 5667856
  object_id: df4344f1-26d6-453c-52da-e728cb94332a
  sha: sha256:2b49a5e5343f027ddd4dc64be938e6ae668ac14e1117e8541c29308442f4a381
docker/autoconf-2.69.tar.gz:
  size: 1927468
  object_id: f762b758-4190-468f-556a-0f1cb17f2a1a
  sha: sha256:954bd69b391edc12d6a4a51a2dd1476543da5c6bbf05a95b59dc0dd6fd4c2969
docker/bridge-utils-1.5.tar.gz:
  size: 33472
  object_id: 8235dfbc-d475-4b0f-7682-cc912fc8fdcd
  sha: sha256:80c18ef50bff135f406bfc503ca832f9e3a33f314cce85717a4dbd2b36409bd2
docker/docker-19.03.5.tgz:
  size: 63252595
  object_id: 427f7190-8cbf-49c5-60a8-41ed40db58d0
  sha: sha256:50cdf38749642ec43d6ac50f4a3f1f7f6ac688e8d8b4e1c5b7be06e1a82f06e9
etcd/etcd-v3.4.3-linux-amd64.tar.gz:
  size: 17280028
  object_id: 6919516e-a048-46df-56a8-170cf71d58ff
  sha: sha256:6c642b723a86941b99753dff6c00b26d3b033209b15ee33325dc8e7f4cd68f07
etcd/etcd-v3.4.5-linux-amd64.tar.gz:
  size: 17306787
  object_id: 0df9baa9-0bdf-4f70-7d75-27c41f27dd57
  sha: sha256:3d65174481aac0f8d1d61f561d4d5d024d2ab77d86bb23f1cb8f0771422c08d8
flannel-v0.11.0-linux-amd64.tar.gz:
  size: 9565743
  object_id: 83064ebe-b45d-4d41-694a-b1e61a781250
  sha: 3024034b2202d5940acf5353037161ea1770a9c5
ipset/ipset_6.20.1-1_amd64.deb:
  size: 34156
  object_id: 5dfcce8f-366e-49f0-59e6-9e2d48178750
  sha: 79eb9008d1a57b31bc748b49c18701ab3dd41108
ipset/libipset3_6.20.1-1_amd64.deb:
  size: 50812
  object_id: 67efec49-e111-45fc-701d-7d55dbe66660
  sha: e4daa1ac22b2775d1c334aa6fe055ca8dcccc185
jq-linux64-1.6:
  size: 3953824
  object_id: efdcc8cd-7155-47d4-65c9-d3d74700633f
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
libmnl0_1.0.3-5_amd64.deb:
  size: 11970
  object_id: 30b1e2c0-4194-47f2-544f-f55eb76b9101
  sha: sha256:abd749bdd206e51fc9ac19ef27d4452a2d9df46b5b1a276d50a065af901ab1c4
libtool-2.4.6.tar.gz:
  size: 1806697
  object_id: 670cc8a2-75d8-4fb5-465f-270395cb9373
  sha: 25b6931265230a06f0fc2146df64c04e5ae6ec33
nfs-debs/keyutils_1.5.9-8ubuntu1_amd64.deb:
  size: 47054
  object_id: e1b42c34-4e88-426b-7268-99d1bdfd40c1
  sha: ec2e96e73feb5215605c9f0254cad05d9cc5688a
nfs-debs/libevent-2.0-5_2.0.21-stable-2ubuntu0.16.04.1_amd64.deb:
  size: 114014
  object_id: 0fa38188-cd2c-417f-7407-02367bc99c7d
  sha: sha256:e1acdffde386a4da7de46166ffd199771a13498f5d4fc38d61b3fa0eba305572
nfs-debs/libnfsidmap2_0.25-5_amd64.deb:
  size: 32182
  object_id: 59ba4d66-fb63-4a62-75da-8502169d85cd
  sha: f28b7370542daaf81cefb44d9057fa9b3fb43064
nfs-debs/nfs-common_1:1.2.8-9ubuntu12.1_amd64.deb:
  size: 184334
  object_id: 6c99be77-1ba2-4be4-409a-36c090035646
  sha: 38f7234fade7c15ffecf4c043c877b01ead92d3d
nfs-debs/rpcbind_0.2.3-0.2_amd64.deb:
  size: 40252
  object_id: 56ad455e-38be-40da-7815-a9d4774d55e4
  sha: 8fa58cfcb1862c6d337d10496fada5f1a6e94a03
pkg-config-0.29.2.tar.gz:
  size: 2016830
  object_id: 2a0b553f-c65d-42ef-6317-dd0cfcdc7c06
  sha: 76e501663b29cb7580245720edfb6106164fad2b
socat-1.7.3.2.tar.gz:
  size: 615818
  object_id: a6f3dcb3-54a0-44a3-4100-f408932aaf8f
  sha: a2446f65fb9fe9703b85ac5664c8920089fe32d8
talloc-2.1.9.tar.gz:
  size: 440335
  object_id: f2d8d5e1-1cb6-450c-480f-015534a76b17
  sha: e1e79fec4c0b6bd92be904a9c03b0a168478711a
