autoconf-2.69.tar.gz:
  size: 1927468
  object_id: 2e4a01bd-aa1e-4fbc-5f56-80aa40d805e3
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
automake-1.15.tar.gz:
  size: 2244206
  object_id: 50feb35a-e388-4fb0-4313-3a47e82fad22
  sha: b5a840c7ec4321e78fdc9472e476263fa6614ca1
cifs-utils-6.7.tar.bz2:
  size: 363647
  object_id: c529967d-57fa-4b41-685e-ff0a507ffaad
  sha: 9ba5091d7c2418a90773c861f04a3f4a36854c14
cni/cni-plugins-amd64-v0.8.7+vmware.4.tgz:
  size: 39816898
  object_id: fb2ad05e-3ec1-42a5-49fb-ec7864f3138e
  sha: sha256:03f2644df790c239b765dd7b17db9656065b7c5d8abbddaf5f9ccef97b87e545
cni/nsenter-2.27.1:
  size: 27520
  object_id: f78a843e-4bf1-47c4-578b-786fcf8a2c94
  sha: sha256:9999ffda41275f924bcbb1d9d7b129421838d917236511eccacae7dc0ad631a9
common-core-kubernetes-1.20.2+vmware.1/kube-apiserver:
  size: 118108160
  object_id: b80e01cb-ef44-41ed-5736-344f6fc9ece1
  sha: sha256:187da2cdf360a1a6b2dd4f834737462f2f57ca6c61d875419c957b8d35efab5c
common-core-kubernetes-1.20.2+vmware.1/kube-controller-manager:
  size: 112287744
  object_id: f9b1c95a-0d38-4c5b-5168-a288a6541a70
  sha: sha256:e5e734b8e57670dc980bc86d04c766708ff0a0628cdd8e6723e723bac3bfceb3
common-core-kubernetes-1.20.2+vmware.1/kube-proxy:
  size: 39477248
  object_id: 0f63f0b3-0151-41ad-4f65-ff84767176e6
  sha: sha256:ace55f41e8a149fc36ca0bb3f5ed39e4949720be897a765d37c357ba488d3c57
common-core-kubernetes-1.20.2+vmware.1/kube-scheduler:
  size: 42831872
  object_id: 035f2528-f48c-4ca2-7cef-dfcfef6ca59d
  sha: sha256:ff26195f25b034518441d249e07f4ba3e7a5b4bcf0fb1d7d87b3536965fa54ed
common-core-kubernetes-1.20.2+vmware.1/kubectl:
  size: 40222720
  object_id: 18174c01-e19e-4d6f-78cc-8c6abe13f9b1
  sha: sha256:22f457fb69a5310285b265b6a89bdd1652a37c6a153f50b3a9437838cb4ef0d4
common-core-kubernetes-1.20.2+vmware.1/kubelet:
  size: 113990600
  object_id: 486a8c5b-5344-4058-7d0d-0bb1c0f35dbd
  sha: sha256:bafedc1fd630e864b2eaf1f2ae409cb37ce10a202912696893b3d646124744d2
conntrack/conntrack_1.4.3-3_amd64.deb:
  size: 27346
  object_id: 0c4aa633-3de8-4a8c-7170-36b3fc9e4a9c
  sha: sha256:ad9eae1cf2191981dd687b681ee701a2f3adfca5b89b45c2ff74c0f8d32113ff
conntrack/libnetfilter-conntrack3_1.0.5-1_amd64.deb:
  size: 36634
  object_id: 1d6d9546-e933-46bd-60f9-00bd8eb91c59
  sha: sha256:18609b2b131bc0dedf4a2c3fbf61b30d16c3d3a96cd43d604e8fc53ebc1e30eb
container-images/simple-server.tgz:
  size: 11953836
  object_id: d362a1a2-0a96-4e73-67a6-2e8565edc489
  sha: sha256:8c0c566079241cb5ec0c6708b47e2ee71b5dc470caa1cef62b0b2c671e784ef8
container-images/vmware_coredns:1.7.0_vmware.7.tgz:
  size: 12773407
  object_id: 44bcdb82-1c01-4331-4b52-b304d270669e
  sha: sha256:f884794a2d97219e22c60cfdb097229e3a4227c5dffc7d78bafe8e6ccbc654a7
container-images/vmware_metrics-server-amd64:v0.3.6.tgz:
  size: 12062146
  object_id: 301b9879-c1bf-42bb-6d90-f05929118056
  sha: sha256:cc477697ea176696030955ed413dc3be064c91a32735458f6450602eddd8f11d
container-images/vmware_pause:3.2.tar.gz:
  size: 286604
  object_id: 27038a71-2c6d-4ada-4e4d-705925c8b315
  sha: sha256:a35cc98a91d6c6b9cecccfae0a11ffb2b7c553b77bdf49d4223b762f11d4e7cb
ctop/ctop-0.5.1-linux-amd64:
  size: 5667856
  object_id: df4344f1-26d6-453c-52da-e728cb94332a
  sha: sha256:2b49a5e5343f027ddd4dc64be938e6ae668ac14e1117e8541c29308442f4a381
docker/autoconf-2.69.tar.gz:
  size: 1927468
  object_id: f762b758-4190-468f-556a-0f1cb17f2a1a
  sha: sha256:954bd69b391edc12d6a4a51a2dd1476543da5c6bbf05a95b59dc0dd6fd4c2969
docker/bridge-utils-1.5.tar.gz:
  size: 33472
  object_id: 8235dfbc-d475-4b0f-7682-cc912fc8fdcd
  sha: sha256:80c18ef50bff135f406bfc503ca832f9e3a33f314cce85717a4dbd2b36409bd2
docker/docker-19.03.14.tgz:
  size: 62435231
  object_id: 440b7210-69ea-4a69-417e-fc6503c8401f
  sha: sha256:9f1ec28e357a8f18e9561129239caf9c0807d74756e21cc63637c7fdeaafe847
etcd/etcd-v3.4.13-linux-amd64.tar.gz:
  size: 17373136
  object_id: dbe2cf3f-a669-4075-5c27-d88cbc577a2e
  sha: sha256:2ac029e47bab752dacdb7b30032f230f49e2f457cbc32e8f555c2210bb5ff107
flannel-v0.11.0-linux-amd64.tar.gz:
  size: 9565743
  object_id: 83064ebe-b45d-4d41-694a-b1e61a781250
  sha: 3024034b2202d5940acf5353037161ea1770a9c5
ipset/ipset_6.20.1-1_amd64.deb:
  size: 34156
  object_id: 5dfcce8f-366e-49f0-59e6-9e2d48178750
  sha: 79eb9008d1a57b31bc748b49c18701ab3dd41108
ipset/libipset3_6.20.1-1_amd64.deb:
  size: 50812
  object_id: 67efec49-e111-45fc-701d-7d55dbe66660
  sha: e4daa1ac22b2775d1c334aa6fe055ca8dcccc185
jq-linux64-1.6:
  size: 3953824
  object_id: efdcc8cd-7155-47d4-65c9-d3d74700633f
  sha: 056ba5d6bbc617c29d37158ce11fd5a443093949
libmnl0_1.0.3-5_amd64.deb:
  size: 11970
  object_id: 30b1e2c0-4194-47f2-544f-f55eb76b9101
  sha: sha256:abd749bdd206e51fc9ac19ef27d4452a2d9df46b5b1a276d50a065af901ab1c4
libtool-2.4.6.tar.gz:
  size: 1806697
  object_id: 670cc8a2-75d8-4fb5-465f-270395cb9373
  sha: 25b6931265230a06f0fc2146df64c04e5ae6ec33
nfs-debs/keyutils_1.5.9-8ubuntu1_amd64.deb:
  size: 47054
  object_id: e1b42c34-4e88-426b-7268-99d1bdfd40c1
  sha: ec2e96e73feb5215605c9f0254cad05d9cc5688a
nfs-debs/libevent-2.0-5_2.0.21-stable-2ubuntu0.16.04.1_amd64.deb:
  size: 114014
  object_id: 0fa38188-cd2c-417f-7407-02367bc99c7d
  sha: sha256:e1acdffde386a4da7de46166ffd199771a13498f5d4fc38d61b3fa0eba305572
nfs-debs/libnfsidmap2_0.25-5_amd64.deb:
  size: 32182
  object_id: 59ba4d66-fb63-4a62-75da-8502169d85cd
  sha: f28b7370542daaf81cefb44d9057fa9b3fb43064
nfs-debs/nfs-common_1:1.2.8-9ubuntu12.1_amd64.deb:
  size: 184334
  object_id: 6c99be77-1ba2-4be4-409a-36c090035646
  sha: 38f7234fade7c15ffecf4c043c877b01ead92d3d
nfs-debs/rpcbind_0.2.3-0.2_amd64.deb:
  size: 40252
  object_id: 56ad455e-38be-40da-7815-a9d4774d55e4
  sha: 8fa58cfcb1862c6d337d10496fada5f1a6e94a03
pkg-config-0.29.2.tar.gz:
  size: 2016830
  object_id: 2a0b553f-c65d-42ef-6317-dd0cfcdc7c06
  sha: 76e501663b29cb7580245720edfb6106164fad2b
socat-1.7.3.2.tar.gz:
  size: 615818
  object_id: a6f3dcb3-54a0-44a3-4100-f408932aaf8f
  sha: a2446f65fb9fe9703b85ac5664c8920089fe32d8
talloc-2.1.9.tar.gz:
  size: 440335
  object_id: f2d8d5e1-1cb6-450c-480f-015534a76b17
  sha: e1e79fec4c0b6bd92be904a9c03b0a168478711a
